[project]
name = "todo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crispy-bootstrap4>=2025.6",
    "django>=5.2.4",
    "django-cors-headers>=4.7.0",
    "django-crispy-forms>=2.4",
]
